; Keep module loading simple. Load what the image provides,
; but explicitly disable chan_sip so PJSIP is the only SIP stack in use.

[modules]
autoload=yes
noload => app_stasis.so
noload => chan_alsa.so
noload => chan_console.so
noload => chan_iax2.so
noload => chan_mgcp.so
noload => chan_oss.so
noload => chan_sip.so
noload => chan_skinny.so
noload => chan_unistim.so
noload => format_ogg_vorbis.so
noload => pbx_ael.so
noload => pbx_dundi.so
noload => res_ari.so
noload => res_ari_applications.so
noload => res_ari_asterisk.so
noload => res_ari_bridges.so
noload => res_ari_channels.so
noload => res_ari_device_states.so
noload => res_ari_endpoints.so
noload => res_ari_events.so
noload => res_ari_mailboxes.so
noload => res_ari_model.so
noload => res_ari_playbacks.so
noload => res_ari_recordings.so
noload => res_ari_sounds.so
noload => res_ari_websockets.so
noload => res_hep.so
noload => res_hep_pjsip.so
noload => res_hep_rtcp.so
noload => res_phoneprov.so
noload => res_pjsip_phoneprov_provider.so
noload => res_stasis.so
noload => res_stasis_answer.so
noload => res_stasis_device_state.so
noload => res_stasis_mailbox.so
noload => res_stasis_playback.so
noload => res_stasis_recording.so
noload => res_stasis_snoop.so
noload => res_stasis_test.so
